import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import DropZone from "../components/DropZone";
import styles from "../styles/Home.module.css";

// @ts-ignore
export default function solution(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <DropZone />
      </div>
    </div>
  );
}
